package fr.doranco.myquizz.view;

public interface IQuizzConstants {
     String  PREF_KEY_USER_FIRSTNAME = "PREF_KEY_USER_FIRSTNAME";
     String  PREF_KEY_USER_SCORE = "PREF_KEY_USER_SCORE";
     int  QUIZZ_ACTIVITY_REQUEST_CODE = 7;
     String STATE_SCORE_BEFORE_ROTATION = "STATE_SCORE_BEFORE_ROTATION";
     String STATE_QUESTION_BEFORE_ROTATION = "STATE_QUESTION_BEFORE_ROTATION";
}
